[package]
name = "wasmos"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = "0.11" #Menu
clearscreen = "4.0.2" #Clear Screen

#For .wasm file detection
directories = "5.0" 
walkdir = "2.3"